spring.jpa.hibernate.ddl-auto=create
spring.jwt.secret="secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"
sentry.dsn=

# Format SQL in testing
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Debug Redis Query
logging.level.org.springframework.data.redis.core=DEBUG
logging.level.org.springframework.data.redis.connection=TRACE