spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url : jdbc:mysql://${MASTER_DB_CONNECTION}/${MASTER_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
        username : ${DB_USERNAME}
        password : ${DB_PASSWORD}
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${SLAVE_DB_CONNECTION}/${SLAVE_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      dialect: org.hibernate.dialect.MySQLDialect


  jwt:
    secret: ${JWT_SECRET}

  data:
    redis:
      ssl:
        enabled: true
      cluster:
        nodes: ${REDIS_HOST}
        max-redirects: 3

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "prometheus"
          - "metrics"

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

sentry:
  dsn: ${SENTRY_REPOSITORY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  servername: ${SENTRY_SERVERNAME}

ai:
  domain: ${AI_DOMAIN}
  port : ${AI_PORT}
  recommend:
    path: ${AI_RECOMMEND_PATH}
