name: Run Test Code

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up jdk'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # https://github.com/actions/setup-java

      # base64 형태 저장된 application.yml 가져와 저장
#      - name: Set YML
#        run: |
#          mkdir -p src/main/resources
#          echo "${{secrets.APPLICATION_YML}}" | base64 --decode > src/main/resources/application.yml

      - name: Set Gradlew Executable Permissions
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew --info test

      - name: Test 결과 출력
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'
